/* Generated By:JavaCC: Do not edit this line. Parser.java */
package org.syno.sync.redo.parsing.parser;
import org.syno.sync.redo.parsing.ast.*;
import java.util.Arrays;
import java.util.List;
import java.util.ArrayList;
import java.io.InputStreamReader;

public class Parser implements ParserConstants {
  public static void parseAST(InputStreamReader in)
  {
    Parser parser = new Parser(in);
  }

  public static Expression mkBinaryOperation(
  BinaryOperator op,
  List < Expression > operands,
  int beginIndex)
  {
    if (beginIndex == operands.size() - 1)
    {
      return operands.get(beginIndex);
    }
    Expression expGauche = operands.get(beginIndex);
    Expression expDroite = mkBinaryOperation(op, operands, beginIndex + 1);
    return new BinaryOperatorApplication(op, expGauche, expDroite);
  }

  public static Expression mkBinaryOperation(BinaryOperator op,
  List < Expression > operands)
  {
    return mkBinaryOperation(op, operands, 0);
  }

/** PARSING **/
  static final public Program program() throws ParseException {
  List < Node > nodes;
    nodes = nodelist();
    jj_consume_token(0);
    {if (true) return new Program(nodes);}
    throw new Error("Missing return statement in function");
  }

  static final public List < Node > nodelist() throws ParseException {
  Node firstNode;
  List < Node > liste;
    if (jj_2_1(3)) {
      firstNode = node();
      liste = nodelist();
    liste.add(firstNode);
    {if (true) return liste;}
    } else {
    {if (true) return new ArrayList < Node > ();}
    }
    throw new Error("Missing return statement in function");
  }

  static final public Node node() throws ParseException {
  String nodeName;
    jj_consume_token(NODE);
    nodeName = ident();
    jj_consume_token(LPAR);
    paramList();
    jj_consume_token(RPAR);
    jj_consume_token(RETURNS);
    nonNullParamList();
    jj_consume_token(LBRACKET);
    eqList();
    jj_consume_token(RBRACKET);
    {if (true) return new Node();}
    throw new Error("Missing return statement in function");
  }

  static final public List < Parameter > paramList() throws ParseException {
  List < Parameter > paramList;
    if (jj_2_2(3)) {
      paramList = nonNullParamList();
    {if (true) return paramList;}
    } else {
    {if (true) return new ArrayList < Parameter > ();}
    }
    throw new Error("Missing return statement in function");
  }

  static final public List < Parameter > nonNullParamList() throws ParseException {
  List < Parameter > param, paramList2;
    param = param();
    jj_consume_token(SEMICOL);
    paramList2 = nonNullParamList();
    for (Parameter p : param)
    paramList2.add(p);
    {if (true) return paramList2;}
    param = param();
    {if (true) return param;}
    throw new Error("Missing return statement in function");
  }

  static final public List < Parameter > param() throws ParseException {
  List < String > identifiers;
  Type type;
    identifiers = nonVoidIdentifierList();
    jj_consume_token(COLON);
    type = type();
    List < Parameter > params = new ArrayList < Parameter > ();
    for (String idt : identifiers)
    params.add(new Parameter(idt, type));
    {if (true) return params;}
    throw new Error("Missing return statement in function");
  }

  static final public List < String > nonVoidIdentifierList() throws ParseException {
  String identifier;
  List < String > idList;
    if (jj_2_3(3)) {
      identifier = ident();
    {if (true) return Arrays.asList(identifier);}
    } else if (jj_2_4(3)) {
      identifier = ident();
      jj_consume_token(COMMA);
      idList = nonVoidIdentifierList();
    idList.add(identifier);
    {if (true) return idList;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public String ident() throws ParseException {
  Token id;
    id = jj_consume_token(IDENT);
    {if (true) return id.image;}
    throw new Error("Missing return statement in function");
  }

  static final public Type type() throws ParseException {
    if (jj_2_5(3)) {
      jj_consume_token(BOOL);
    {if (true) return Type.BOOL;}
    } else if (jj_2_6(3)) {
      jj_consume_token(INT);
    {if (true) return Type.INT;}
    } else if (jj_2_7(3)) {
      jj_consume_token(REAL);
    {if (true) return Type.REAL;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public List < Equation > eqList() throws ParseException {
  Equation eq;
  List < Equation > lst;
    if (jj_2_8(3)) {
      eq = equation();
      lst = eqList();
    lst.add(eq);
    {if (true) return lst;}
    } else {
    {if (true) return new ArrayList < Equation > ();}
    }
    throw new Error("Missing return statement in function");
  }

  static final public Equation equation() throws ParseException {
  Pattern patt;
  Expression exp;
    patt = pattern();
    jj_consume_token(AFFECT);
    exp = expr();
    jj_consume_token(SEMICOL);
    {if (true) return new Equation(patt, exp);}
    throw new Error("Missing return statement in function");
  }

  static final public Pattern pattern() throws ParseException {
  String ident;
  List < String > strList;
    ident = ident();
    {if (true) return new Pattern(Arrays.asList(ident));}
    jj_consume_token(LPAR);
    strList = nonVoidIdentifierList();
    jj_consume_token(RPAR);
    {if (true) return new Pattern(strList);}
    throw new Error("Missing return statement in function");
  }

/**
	%left EVERY
	%left MERGE
	%left WHEN
	
	%right ARROW
	%left IMPL
	%left OR
	%left AND
	%left COMP EQUAL NEQ
	%left PLUS MINUS
	%left STAR SLASH DIV MOD
	
	%nonassoc uminus   
	%nonassoc NOT PRE  not pre 
*/
  static final public Expression expr() throws ParseException {
  Expression e;
    if (jj_2_9(3)) {
      e = conditionalExpr();
    {if (true) return e;}
    } else if (jj_2_10(3)) {
      e = everyExp();
    {if (true) return e;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public Expression conditionalExpr() throws ParseException {
  Expression ebool, ethen, eelse;
    jj_consume_token(IF);
    ebool = expr();
    jj_consume_token(THEN);
    ethen = expr();
    jj_consume_token(ELSE);
    eelse = expr();
    {if (true) return new Conditional(ebool, ethen, eelse);}
    throw new Error("Missing return statement in function");
  }

  static final public Expression everyExp() throws ParseException {
  Expression e1, e2;
  List < Expression > expList = new ArrayList < Expression > ();
    e1 = mergeExp();
    expList.add(e1);
    label_1:
    while (true) {
      if (jj_2_11(3)) {
        ;
      } else {
        break label_1;
      }
      jj_consume_token(EVERY);
      e2 = mergeExp();
      expList.add(e2);
    }
    {if (true) return mkBinaryOperation(BinaryOperator.PLUS, expList);}
    throw new Error("Missing return statement in function");
  }

/**
	Syntaxe : MERGE(expr1)(C1 => )²
*/
/**
TODO:
	MERGE
	WHEN
**/
  static final public Expression mergeExp() throws ParseException {
  Expression e;
    e = arrowExp();
    {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

// Assoc droite ! 
  static final public Expression arrowExp() throws ParseException {
  Expression e1, e2;
  List < Expression > expList = new ArrayList < Expression > ();
    label_2:
    while (true) {
      e1 = orExp();
      jj_consume_token(ARROW);
      expList.add(e1);
      if (jj_2_12(3)) {
        ;
      } else {
        break label_2;
      }
    }
    e2 = orExp();
    expList.add(e1);
    {if (true) return mkBinaryOperation(BinaryOperator.FOLLOWED_BY, expList);}
    throw new Error("Missing return statement in function");
  }

  static final public Expression orExp() throws ParseException {
  Expression e1, e2;
    e1 = andExp();
    label_3:
    while (true) {
      if (jj_2_13(3)) {
        ;
      } else {
        break label_3;
      }
      jj_consume_token(OR);
      e2 = andExp();
      e1 = new BinaryOperatorApplication(BinaryOperator.OR, e1, e2);
    }
    {if (true) return e1;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression andExp() throws ParseException {
  Expression e1, e2;
  List < Expression > expList = new ArrayList < Expression > ();
    e1 = equalExp();
    expList.add(e1);
    label_4:
    while (true) {
      if (jj_2_14(3)) {
        ;
      } else {
        break label_4;
      }
      jj_consume_token(AND);
      e2 = equalExp();
      expList.add(e2);
    }
    {if (true) return mkBinaryOperation(BinaryOperator.AND, expList);}
    throw new Error("Missing return statement in function");
  }

  static final public Expression equalExp() throws ParseException {
  Expression e1, e2;
    e1 = compExp();
    label_5:
    while (true) {
      if (jj_2_15(3)) {
        jj_consume_token(EQUAL);
        e2 = compExp();
        e1 = new BinaryOperatorApplication(BinaryOperator.EQ, e1, e2);
      } else if (jj_2_16(3)) {
        jj_consume_token(NEQ);
        e2 = compExp();
        e1 = new BinaryOperatorApplication(BinaryOperator.NEQ, e1, e2);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      if (jj_2_17(3)) {
        ;
      } else {
        break label_5;
      }
    }
    {if (true) return e1;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression compExp() throws ParseException {
  Expression e1, e2;
    e1 = addExp();
    label_6:
    while (true) {
      if (jj_2_18(3)) {
        jj_consume_token(GT);
        e2 = addExp();
        e1 = new BinaryOperatorApplication(BinaryOperator.GREATER_THAN, e1, e2);
      } else if (jj_2_19(3)) {
        jj_consume_token(GE);
        e2 = addExp();
        e1 = new BinaryOperatorApplication(BinaryOperator.GREATER_OR_EQUAL, e1, e2);
      } else if (jj_2_20(3)) {
        jj_consume_token(LT);
        e2 = addExp();
        e1 = new BinaryOperatorApplication(BinaryOperator.LESSER_THAN, e1, e2);
        jj_consume_token(LE);
        e2 = addExp();
        e1 = new BinaryOperatorApplication(BinaryOperator.LESSER_OR_EQUAL, e1, e2);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      if (jj_2_21(3)) {
        ;
      } else {
        break label_6;
      }
    }
    {if (true) return e1;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression addExp() throws ParseException {
  Expression e1, e2;
  List < Expression > expList = new ArrayList < Expression > ();
    e1 = multExp();
    label_7:
    while (true) {
      jj_consume_token(PLUS);
      e2 = multExp();
        e1 = new BinaryOperatorApplication(BinaryOperator.PLUS, e1, e2);
      jj_consume_token(MINUS);
      e2 = multExp();
        e1 = new BinaryOperatorApplication(BinaryOperator.MINUS, e1, e2);
      if (jj_2_22(3)) {
        ;
      } else {
        break label_7;
      }
    }
    {if (true) return e1;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression multExp() throws ParseException {
  Expression e1, e2;
    e1 = preExp();
    label_8:
    while (true) {
      if (jj_2_23(3)) {
        jj_consume_token(MULTIPLY);
        e2 = preExp();
        e1 = new BinaryOperatorApplication(BinaryOperator.MULT, e1, e2);
      } else if (jj_2_24(3)) {
        jj_consume_token(DIV);
        e2 = preExp();
        e1 = new BinaryOperatorApplication(BinaryOperator.DIV, e1, e2);
      } else if (jj_2_25(3)) {
        jj_consume_token(MOD);
        e2 = preExp();
        e1 = new BinaryOperatorApplication(BinaryOperator.MOD, e1, e2);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      if (jj_2_26(3)) {
        ;
      } else {
        break label_8;
      }
    }
    {if (true) return e1;}
    throw new Error("Missing return statement in function");
  }

  // + - MULT DIV MOD
  static final public Expression preExp() throws ParseException {
  Expression e1, e2;
    e1 = simpleExpr();
    {if (true) return e1;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression simpleExpr() throws ParseException {
  Expression e;
    if (jj_2_27(3)) {
      e = constant();
    {if (true) return e;}
    } else if (jj_2_28(3)) {
      jj_consume_token(LPAR);
      e = expr();
      jj_consume_token(RPAR);
    {if (true) return e;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public Expression constant() throws ParseException {
  Token t;
    t = jj_consume_token(CONST_BOOL);
      {if (true) return new ConstBool(t.image);}
    t = jj_consume_token(CONST_INT);
      {if (true) return new ConstInt(t.image);}
    t = jj_consume_token(CONST_FLOAT);
      {if (true) return new ConstFloat(t.image);}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  static private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  static private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  static private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  static private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  static private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  static private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  static private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  static private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  static private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  static private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  static private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  static private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  static private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  static private boolean jj_3_25() {
    if (jj_scan_token(MOD)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3_16() {
    if (jj_scan_token(NEQ)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3_24() {
    if (jj_scan_token(DIV)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_10()) return true;
    return false;
  }

  static private boolean jj_3_8() {
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3_17() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_15()) {
    jj_scanpos = xsp;
    if (jj_3_16()) return true;
    }
    return false;
  }

  static private boolean jj_3_15() {
    if (jj_scan_token(EQUAL)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3_11() {
    if (jj_scan_token(EVERY)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3_23() {
    if (jj_scan_token(MULTIPLY)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_23()) {
    jj_scanpos = xsp;
    if (jj_3_24()) {
    jj_scanpos = xsp;
    if (jj_3_25()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_22() {
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3R_15() {
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_9() {
    if (jj_scan_token(NODE)) return true;
    if (jj_3R_11()) return true;
    if (jj_scan_token(LPAR)) return true;
    return false;
  }

  static private boolean jj_3_7() {
    if (jj_scan_token(REAL)) return true;
    return false;
  }

  static private boolean jj_3_6() {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  static private boolean jj_3_14() {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3R_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3_7()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_scan_token(BOOL)) return true;
    return false;
  }

  static private boolean jj_3R_14() {
    if (jj_scan_token(IF)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_9()) return true;
    return false;
  }

  static private boolean jj_3R_11() {
    if (jj_scan_token(IDENT)) return true;
    return false;
  }

  static private boolean jj_3_22() {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3_10() {
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3R_21() {
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_25() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3_10()) return true;
    }
    return false;
  }

  static private boolean jj_3_9() {
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_3_13() {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3R_17() {
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_scan_token(CONST_BOOL)) return true;
    if (jj_scan_token(CONST_INT)) return true;
    if (jj_scan_token(CONST_FLOAT)) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3R_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) return true;
    }
    return false;
  }

  static private boolean jj_3_20() {
    if (jj_scan_token(LT)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3_28() {
    if (jj_scan_token(LPAR)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  static private boolean jj_3R_29() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_27()) {
    jj_scanpos = xsp;
    if (jj_3_28()) return true;
    }
    return false;
  }

  static private boolean jj_3_12() {
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_3_27() {
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3R_26() {
    if (jj_3R_12()) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_30()) return true;
    return false;
  }

  static private boolean jj_3R_28() {
    Token xsp;
    if (jj_3_12()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_12()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_19() {
    if (jj_scan_token(GE)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_27() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(LPAR)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3_18() {
    if (jj_scan_token(GT)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3_21() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_18()) {
    jj_scanpos = xsp;
    if (jj_3_19()) {
    jj_scanpos = xsp;
    if (jj_3_20()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_20() {
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_16() {
    if (jj_3R_28()) return true;
    return false;
  }

  static private boolean jj_3R_10() {
    if (jj_3R_26()) return true;
    return false;
  }

  static private boolean jj_3R_13() {
    if (jj_3R_27()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public ParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[28];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[45];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 45; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 28; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
